development:
  sessions:
    default:
      database: sample_app_development
      hosts:
        - localhost:27017
      options:
        consistency: strong

test:
  sessions:
    default:
      database: sample_app_test
      hosts:
        - localhost:27017
      options:
        consistency: strong

production:
  sessions:
    default:
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      database: sample_app_production
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      port: <%= ENV['MONGOID_PORT'] %>
      options:
        consistency: strong
